import dotenv from 'dotenv';

dotenv.config({ path: '.env' });

export const cloudConfig = {
	IMAGE_CLOUDINARY_CLOUD_NAME: process.env.IMAGE_CLOUDINARY_CLOUD_NAME!,
	IMAGE_CLOUDINARY_API_KEY: process.env.IMAGE_CLOUDINARY_API_KEY!,
	IMAGE_CLOUDINARY_API_SECRET: process.env.IMAGE_CLOUDINARY_API_SECRET!,

	MODEL_AWS_BUCKET_REGION: process.env.MODEL_AWS_BUCKET_REGION!,
	MODEL_AWS_BUCKET_NAME: process.env.MODEL_AWS_BUCKET_NAME!,
	MODEL_AWS_BUCKET_ACCESS_KEY: process.env.MODEL_AWS_BUCKET_ACCESS_KEY!,
	MODEL_AWS_BUCKET_SECRET_KEY: process.env.MODEL_AWS_BUCKET_SECRET_KEY!
};
