name: Actions for Working Space API
on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    Working-Space-API-Actions:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: Create .env files
              shell: bash
              run: cp ../.env .env

            - run: npm ci
            - run: npm run test:unit
            - run: npm run build:prod
            - run: pm2 startOrRestart ecosystem.config.js
